# Build physics.cpp -> physics/physics.wasm, embedded as base64 in game/js/physics/physics-binary.js.
# Needs clang and wasm-ld on PATH (install LLVM: winget install LLVM.LLVM).
# No Emscripten required.
$ErrorActionPreference = "Stop"
$Here = $PSScriptRoot
$Out  = Join-Path $Here "..\game\js\physics"
$Wasm = Join-Path $Here "physics.wasm"

& clang --target=wasm32 -O3 -flto -nostdlib -fno-exceptions -fno-rtti -ffast-math `
  -fvisibility=hidden "-Wl,--no-entry" "-Wl,--export-dynamic" "-Wl,--lto-O3" `
  "-Wl,--initial-memory=262144" "-Wl,-z,stack-size=32768" `
  -o $Wasm (Join-Path $Here "physics.cpp")
if ($LASTEXITCODE -ne 0) { throw "clang failed ($LASTEXITCODE)" }

$b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($Wasm))
$js  = "// Generated by physics/build.ps1 from physics/physics.cpp - do not edit.`nwindow.PP_PHYSICS_WASM_B64 = `"$b64`";`n"
[IO.File]::WriteAllText((Join-Path $Out "physics-binary.js"), $js)
Write-Host "Built $Wasm ($((Get-Item $Wasm).Length) bytes)" -ForegroundColor Green
