#!/usr/bin/env sh
# Build physics.cpp -> physics/physics.wasm, embedded as base64 in game/js/physics/physics-binary.js.
# Needs clang and wasm-ld (LLVM 14+). No Emscripten required.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/../game/js/physics"
clang --target=wasm32 -O3 -flto -nostdlib -fno-exceptions -fno-rtti -ffast-math \
  -fvisibility=hidden -Wl,--no-entry -Wl,--export-dynamic -Wl,--lto-O3 \
  -Wl,--initial-memory=262144 -Wl,-z,stack-size=32768 \
  -o "$HERE/physics.wasm" "$HERE/physics.cpp"
B64="$(base64 < "$HERE/physics.wasm" | tr -d '\n')"
printf '// Generated by physics/build.sh from physics/physics.cpp - do not edit.\nwindow.PP_PHYSICS_WASM_B64 = "%s";\n' "$B64" > "$OUT/physics-binary.js"
echo "Built $OUT/physics-binary.js ($(wc -c < "$HERE/physics.wasm") byte wasm)"
