# build.ps1 — Compile physics.cpp → physics.wasm + physics.js (Emscripten loader)
#
# PREREQUISITES
# -------------
# 1. Install Emscripten SDK:  https://emscripten.org/docs/getting_started/downloads.html
#    Typical install on Windows:
#      git clone https://github.com/emscripten-core/emsdk.git
#      cd emsdk
#      .\emsdk install latest
#      .\emsdk activate latest
#      .\emsdk_env.ps1          # activates emcc in the current shell
#
# 2. Run this script from the physics/ directory:
#      cd c:\Users\emi\Desktop\101\PingPong\physics
#      .\build.ps1
#
# OUTPUT
# ------
#   physics.wasm   — binary WebAssembly module loaded via fetch() at runtime
#   physics.js     — ES-module loader generated by Emscripten (auto-instantiates wasm)
#
# Both files are placed in the same directory as this script (physics/).
# physics-wasm.js (your hand-written JS bridge) then imports physics.js.

$ErrorActionPreference = "Stop"

# ── Paths ──────────────────────────────────────────────────────────────────────
$ScriptDir = $PSScriptRoot
$Source    = Join-Path $ScriptDir "physics.cpp"
$OutJs     = Join-Path $ScriptDir "physics.js"
$BgSource  = Join-Path $ScriptDir "background_sim.cpp"
$BgOutJs   = Join-Path $ScriptDir "background-sim.js"

Write-Host "Building $Source → physics.wasm / physics.js ..." -ForegroundColor Cyan

# ── Emscripten compile command ──────────────────────────────────────────────────
#
# Flags explained:
#   -O3                               Full optimisation (crucial for hot paths)
#   -s WASM=1                         Emit .wasm binary (not asm.js)
#   -s MODULARIZE=1                   Wrap the loader in a factory function
#   -s EXPORT_NAME="PhysicsModule"    Factory function name callable from JS
#   -s EXPORTED_FUNCTIONS             C functions to expose (prefix with _)
#   -s EXPORTED_RUNTIME_METHODS       Emscripten utilities needed by the bridge
#   -s ALLOW_MEMORY_GROWTH=1          Allow heap to grow if needed at runtime
#   -s SINGLE_FILE=0                  Keep .wasm separate (better caching)
#   --no-entry                        No main() needed

# Build the argument list as an array to avoid PowerShell comma/quoting pitfalls
$emccArgs = @(
    $Source,
    '-O3',
    '-sWASM=1',
    '-sMODULARIZE=1',
    '-sEXPORT_NAME=PhysicsModule',
    '-sEXPORTED_FUNCTIONS=_ball_integrate,_gravity_well_apply,_ball_paddle_collide,_predict_ball_y,_ball_reset,_update_fire_tongues,_malloc,_free',
    '-sEXPORTED_RUNTIME_METHODS=cwrap,HEAPF32',
    '-sALLOW_MEMORY_GROWTH=1',
    '-sSINGLE_FILE=0',
    '--no-entry',
    '-o', $OutJs
)

& emcc @emccArgs

if ($LASTEXITCODE -eq 0) {
    Write-Host "Physics build succeeded." -ForegroundColor Green
    Write-Host "  $OutJs"
    Write-Host "  $(Join-Path $ScriptDir 'physics.wasm')"
} else {
    Write-Error "emcc failed with exit code $LASTEXITCODE"
}

Write-Host "Building $BgSource → background-sim.wasm / background-sim.js ..." -ForegroundColor Cyan

$bgEmccArgs = @(
    $BgSource,
    '-O3',
    '-sWASM=1',
    '-sMODULARIZE=1',
    '-sEXPORT_NAME=BackgroundSimModule',
    '-sEXPORTED_FUNCTIONS=_update_speed_rain,_update_gravity_stars,_update_intro_curves,_malloc,_free',
    '-sEXPORTED_RUNTIME_METHODS=cwrap,HEAPF32,HEAP32',
    '-sALLOW_MEMORY_GROWTH=1',
    '-sSINGLE_FILE=0',
    '--no-entry',
    '-o', $BgOutJs
)

& emcc @bgEmccArgs

if ($LASTEXITCODE -eq 0) {
    Write-Host "Background sim build succeeded." -ForegroundColor Green
    Write-Host "  $BgOutJs"
    Write-Host "  $(Join-Path $ScriptDir 'background-sim.wasm')"
} else {
    Write-Error "emcc failed with exit code $LASTEXITCODE"
}
